language: python
python:
    - "3.6"

env:
    - DJANGO=1.10.5

before_install:
    - export PIP_USE_MIRRORS=true

install:
    - pip install -r requirements.txt

script:
    - python manage.py migrate --noinput
    - python setup.py sdist

deploy:
  - provider: pypi
    skip_cleanup: true
    user: bsquidwrd
    password:
        secure: ZG/StGeQtfK/kI62F/mdxDzp4aKxzrVAcNvZ5k309DMVeN2YSGfa8XgsQErOoD5ogXsYLTGpE5qS9QbxrvLvebmi+crO2qzxmZPtvwmIG5dkVD9xCgs8F0M6Yx1zR1xdMO5+iSHa4vuImYU2OdpfYCVDRmBXHhG/IoE+8Qxt+j8/ztEcJUg4iL4tnjwgoI0PcHu/RNwNaKMCOwxsxKN78QqCltkp8dOUIr1VYPDFjc3orZfZJdpYrCC1qq7sXXHoCeXN98/0lKS3PUAg9pJm9W2qtumD4BK2jLrcCKniVFrPJ+u55Igg4YdT2ON8tOLhTnIlbyVxl0mZvk2zzCH8w7lMXFKyhoORe6n997JvIuKvUmLtAHH1qMJttayqbEglHxn33sMMb1373ciP+J7kb0ApqvWPH3GwRchNpB8d4rA7htmr8KkJ78bwJ9md8ylGocarpQiccdpRWX+vj4gngcWoUHTbhjjufQL/qWKHix1YrIYKxmq16IEvQBN5UMGZcTWpsikoKyVzaEpoBex/vApjqlk73YVhBK8EzSGMHBVkCW4ogQmisg42kCUBOPU3JCjckWueiaS0PBWfJ3y4b02X2z/TyW7HS3TjCN5M4jKXHn1XKybdt3ltyXSt6N9s2mQZpFVAAhqDaPaKUH3kExNlbFmr8zaNI6sEjmqPsGA=
    on:
        tags: true
        distributions: sdist
        repo: bsquidwrd/django-keybase-verification

  - provider: releases
    api_key: ""
    file: "dist/*.tar.gz"
    skip_cleanup: true
    on:
        tags: true
